version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx ."

python:
  install:
  - requirements: requirements.txt

sphinx:
  builder: html
  fail_on_warning: true