[project]
name = "SolarStations.org"
version = "0.1.0"
description = "A catalog of multi-component solar irradiance monitoring stations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium==0.20.0",
    "itables==2.2.2",
    "jupyter-book==2.1.6",
    "matplotlib==3.11.1",
    "numpy==2.5.1",
    "pandas==3.0.3",
    "pvlib==0.15.2",
    "unidecode==1.4.0",
    "openpyxl==3.1.5",
    "xarray==2026.7.0",
    "h5netcdf==1.8.1",
    "jupyter-book==2.1.6",
    "jupyter-book-marimo==0.0.3",
    "marimo",
    "kgcpy==1.1.8",
]
