# This file was created automatically with `jupyter-book init --gh-pages` 🪄 💚
# Ensure your GitHub Pages settings for this repository are set to deploy with **GitHub Actions**.

name: Jupyter Book (via myst) GitHub Pages Deploy
on:
  push:
    # Runs on pushes targeting the default branch
    branches: [main]
env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  BASE_URL: /${{ github.event.repository.name }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Set up Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Install mystmd
        run: npm install -g mystmd
      - name: Build HTML Assets
        env:  # Set secret environment variables
          BSRN_FTP_USERNAME: ${{ secrets.BSRN_FTP_USERNAME }}
          BSRN_FTP_PASSWORD: ${{ secrets.BSRN_FTP_PASSWORD }}
        run: cd docs && myst build --html --execute
      - name: Add CNAME
        run: echo 'SolarStations.org' > ./docs/_build/html/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
